spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5433/mybank
    username: mybank_dev
    password: mybank
  jpa:
    hibernate:
      ddl-auto: none
app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: 3600000